server:
  port: 8081

spring:
  application:
    name: mydemo-dev
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.72.133:3306/mydemo?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      #配置监控页面访问登录名称
      stat-view-servlet.login-username: admin
      #配置监控页面访问密码
      stat-view-servlet.login-password: admin
      #是否开启慢sql查询监控
      filter.stat.log-slow-sql: true
      #慢SQL执行时间
      filter.stat.slow-sql-millis: 1

  redis:
    redisson:
      config: classpath:redisson-config.yml

  #mongo
  data:
    mongodb:
      uri: mongodb://192.168.72.133:27017/demo


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.example.web.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true